### PR TITLE
Increasing the max rspec examples length

### PR DESCRIPTION
**Pull request by jacek-adamek**
Even though I try to have just one test for an example, sometimes it's difficult to express all expectations in 5 lines without loosing readability.

### CODE REVIEW

**Comment by sufleR** [comment]
My point of view is that when we will format our examples like this:
```
it 'calls underlying HttpApiClient with correct parameters' do
       expect(HttpApiClient).to receive(:new)
         .with(instance_of(String),
               "https://#{AppSettings.cloudbet_api.url}/api/v2/sports/markets",
               '')
         .and_return(http_api_client)
       service.call
     end
```
It will be very hard to fit into 5 lines.

**Comment by jacek-adamek** [comment]
I have another example:
```
it 'formats the values in the result' do # rubocop:disable RSpec/ExampleLength
      get :index
      expect(json_response[0]['competitions'][0]['events'][0])
        .to include('event_id' => 1,
                    'one_x_two_1' => '2.300',
                    'one_x_two_x' => nil,
                    'one_x_two_2' => '1.000',
                    'spreads_1' => nil,
                    'spreads_2' => '34.024',
                    'totals_under' => '3.000',
                    'totals_over' => nil)
end
```
I could try to place  these expected results in a one line but I am not sure if it was readable at all.

**Comment by sullerandras** [comment]
Note that this is a public repo, so don't post sensitive content.

**Comment by edbo** [comment]
I'm OK with this if others are. There are plenty of places where 5 causes issues.

**Pull request merged**
