### PR TITLE
Exclude api docs files within Metrics/BlockLength.

### PR DESCRIPTION
**Pull request by kamilpp**
We would like to ignore BlockLength offences in files containing api docs definition (especially swagger blocs can be quite long).

### CODE REVIEW

**Comment by sullerandras** [comment]
Looks reasonable to me. @c-knowles ?

**Comment by c-knowles** [comment]
Seems reasonable. Is it worth starting to add comments into the YAML to note why we've changed the style or enough that it links back to these PRs?

**Comment by sullerandras** [comment]
I think adding a comment there would be nice.

**Comment by kamilpp** [comment]
@sullerandras @c-knowles
I have added a comment as requested. Please fell free to rephrase it if found not enough descriptive.

**Pull request merged**
