### PR TITLE
Disable let setup

### PR DESCRIPTION
**Pull request by edbo**
Description of this one here:

http://www.rubydoc.info/gems/rubocop-rspec/1.7.0/RuboCop/Cop/RSpec/LetSetup

It annoys me because I can't think of any other nice way of creating objects you need when a test is running. For example we use it a lot to create settings in a context for when a test is running.

### CODE REVIEW

**Comment by sullerandras** [comment]
Since unreferenced `let!` is similar to `before`, i would use `before` instead. Simply because the intention is clearer.
With an unreferenced `let!` declaration, someone not familiar with the test structure might spend time trying to figure out why that `let!` is not used. When the same instruction is in a `before` it is clear that it's only a setup and will never be referenced anywhere.

**Comment by edbo** [comment]
How's about if you want to create a variable that must exist before the test and you'd like to reference somewhere?

**Comment by sufleR** [comment]
@edbo in that case rubocop will not mark it as wrong.
From what I know it is only for not referenced `let!`

**Comment by edbo** [comment]
@sufleR Thanks I didn't actually realise that! Closing this out now.

**Pull request closed without merging**
